apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-kqgh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-kqgh
    app.kubernetes.io/part-of: cin4s-839-0022-app
  name: devfile-sample-kqgh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-kqgh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-kqgh
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0022-tenant/cin4s-839-0022-app/devfile-sample-kqgh@sha256:d6674c485bd46ec9e328b9f1423810246b6cfff4d3f53852bc9bef550cbd461f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
